### ISSUE TITLE
Class Reference Not Be Found ?

### ISSUE THREAD

**Issue by hzrbasaran** [Mastercard/mastercard-api-csharp#2]
Hi,

CardBrandsOptions class could not be found . => MasterCard => SDK => Services => PartnerWallet => CardBrandsService.cs
Connection class could not be found. => MasterCard => SDK => Services => PartnerWallet => DeletePairingServices.cs
ConnectionHistory class could not be found. => MasterCard => SDK => Services => PartnerWallet => ConnectedMerchantHistoryService.cs

**Comment by sasahua** [comment]
I have the same problem for some class is missing

**Comment by ade90036** [comment]
Hi @sasahua 

This project provides the foundation of our SDKs. 
We call it Core because it provides the reusable components which all the implementing SDKs use. Such as security (JWT, OAuth, FLE), Logging, Https Layer, Object marshalling and unmarshalling. 

Therefore the classes which you are looking are not included within. 

They usually are generated on the fly and packaged and published in a nuget package. 

So is the service / sdk that you are trying to use? MasterPass?

regards

**Comment by ade90036** [comment]
ok... something i  missed myself. this repo is marked as DEPRECATED because it is not in used anymore.
